### ISSUE TITLE
dssp error when run the example

### ISSUE THREAD

**Issue by kanghui-learning** [PKUliujl/GeoPacker#2]
Hi,

I've installed all the packages in requirement.txt. When I run the examples by this command:

python  run_GeoPacker.py --inputPATH example/ -i 3MPC_A.pdb --pdbname 3MPC  --chainID A

the dssp error appeared as below:

Traceback (most recent call last):
  File "/MYPATH/GeoPacker/run_GeoPacker.py", line 85, in <module>
    evaluate(feature_path, pdbname, chainID,seq_tobe_designed,seqname,packered_outPATH,outputfile)
  File "/MYPATH/GeoPacker/run_GeoPacker.py", line 30, in evaluate
    AA_label, data = load_Data(feature_path, inputfile,pdbname, chainID ,seq_tobe_designed)
  File "/MYPATH/GeoPacker/MainScripts/utils.py", line 215, in load_Data
    geometric_f, distance = pre_fea(feature_path,inputfile,pdbID,chainID)
  File "/MYPATH/GeoPacker/MainScripts/utils.py", line 273, in pre_fea
    t1_r = t1.result()
  File "/root/mambaforge/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/root/mambaforge/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
Exception: DSSP failed to produce an output

My mkdssp version is 4.1.0, installed by compiling the source code in https://github.com/PDB-REDO/dssp

I'm newer to this area and I have no idea what happened...

**Comment by PKUliujl** [comment]
I noticed that you have installed the newer version ‘mkdssp’, however, the biopython uses the default executive command  ‘dssp’. 
An easy way to check the aforementioned issue is to see which dssp or mkdssp you are using.
If the system fails to find dssp, but mkdssp, an alternative way for you is typing ‘cp /*path*/mkdssp  /*path*/dssp’, where the /*path*/ is the path including the executive command ‘mkdssp’.

**Comment by PKUliujl** [comment]
> I noticed that you have installed the newer version ‘mkdssp’, however, the biopython uses the default executive command ‘dssp’. 
An easy way to check the aforementioned issue is to see which dssp or mkdssp you are using. 
If the system fails to find dssp, but mkdssp, an alternative way for you is typing ‘cp /_path_/mkdssp /_path_/dssp’, where the /_path_/ is the path including the executive command ‘mkdssp’.



> Hi,
> 
> I've installed all the packages in requirement.txt. When I run the examples by this command:
> 
> python run_GeoPacker.py --inputPATH example/ -i 3MPC_A.pdb --pdbname 3MPC --chainID A
> 
> the dssp error appeared as below:
> 
> Traceback (most recent call last): File "/MYPATH/GeoPacker/run_GeoPacker.py", line 85, in evaluate(feature_path, pdbname, chainID,seq_tobe_designed,seqname,packered_outPATH,outputfile) File "/MYPATH/GeoPacker/run_GeoPacker.py", line 30, in evaluate AA_label, data = load_Data(feature_path, inputfile,pdbname, chainID ,seq_tobe_designed) File "/MYPATH/GeoPacker/MainScripts/utils.py", line 215, in load_Data geometric_f, distance = pre_fea(feature_path,inputfile,pdbID,chainID) File "/MYPATH/GeoPacker/MainScripts/utils.py", line 273, in pre_fea t1_r = t1.result() File "/root/mambaforge/lib/python3.9/concurrent/futures/_base.py", line 446, in result return self.__get_result() File "/root/mambaforge/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result raise self._exception Exception: DSSP failed to produce an output
> 
> My mkdssp version is 4.1.0, installed by compiling the source code in https://github.com/PDB-REDO/dssp
> 
> I'm newer to this area and I have no idea what happened...



> Hi,
> 
> I've installed all the packages in requirement.txt. When I run the examples by this command:
> 
> python run_GeoPacker.py --inputPATH example/ -i 3MPC_A.pdb --pdbname 3MPC --chainID A
> 
> the dssp error appeared as below:
> 
> Traceback (most recent call last): File "/MYPATH/GeoPacker/run_GeoPacker.py", line 85, in evaluate(feature_path, pdbname, chainID,seq_tobe_designed,seqname,packered_outPATH,outputfile) File "/MYPATH/GeoPacker/run_GeoPacker.py", line 30, in evaluate AA_label, data = load_Data(feature_path, inputfile,pdbname, chainID ,seq_tobe_designed) File "/MYPATH/GeoPacker/MainScripts/utils.py", line 215, in load_Data geometric_f, distance = pre_fea(feature_path,inputfile,pdbID,chainID) File "/MYPATH/GeoPacker/MainScripts/utils.py", line 273, in pre_fea t1_r = t1.result() File "/root/mambaforge/lib/python3.9/concurrent/futures/_base.py", line 446, in result return self.__get_result() File "/root/mambaforge/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result raise self._exception Exception: DSSP failed to produce an output
> 
> My mkdssp version is 4.1.0, installed by compiling the source code in https://github.com/PDB-REDO/dssp
> 
> I'm newer to this area and I have no idea what happened...

**Comment by kanghui-learning** [comment]
I do this command "cp /path/mkdssp /path/dssp" and now the system can find mkdssp and dssp both. But that error still appeared.

Now if I type "which dssp" or "which mkdssp", I will get a line “/usr/local/bin/dssp” or "/usr/local/bin/mkdssp"

**Comment by PKUliujl** [comment]
I think the problem that biopython fails to find the executive command ‘dssp’ or ‘mkdssp’ is still existing. I recommend you an empirical way to install ‘dssp’ using ‘conda’ shown in the ‘requirement.txt’, and then ‘cp mkdssp dssp’(please add the path).  Before doing this, delete dssp4.0 executive command you installed.

**Comment by kanghui-learning** [comment]
I wish I could... Actually, I cannot install dssp using conda on my server, that is why I built the package by compiling the source code, which is more difficult. I think it may be because of the network conditions of the server. 

Now I'm trying to build this project on another server in conda way, everything worked well, and this command "cp /*path*/mkdssp /*path*/dssp" is also runned. But when I run the example, that error keeps appearing...  

Exception: DSSP failed to produce an output

Do I need to align all the packages in requirement.txt? Now I use tensorflow==2.6.0, numpy==1.19.5, pandas==1.1.5, three differences.

**Comment by PKUliujl** [comment]
Please use an example to try whether the installed executive `dssp` or `mkdssp` is useful.

Try to add the absolute path  of the executive `dssp` or `mkdssp` to the DSSP module in line 188 of MainScripts/single_f.py.
eg. dssp = DSSP(model,inputfile,dssp='/usr/bin/dssp')

**Comment by PKUliujl** [comment]
Please use an example to try whether the installed executive dssp or mkdssp is useful.

Try to add the absolute path of the executive dssp or mkdssp to the DSSP module in line 118 of MainScripts/single_f.py.
eg. dssp = DSSP(model,inputfile,dssp='/usr/bin/dssp')

**Comment by kanghui-learning** [comment]
Hi,

I used a simple case to test the dssp, and this error also occurred.

## code
    class Test_Dssp():
        def __init__(self):
            self.parser = Bio.PDB.PDBParser()
  
      def test_dssp(self, inputfile, pdbname):
          structure = self.parser.get_structure(pdbname,inputfile)
          for model in structure:
              dssp = DSSP(model,inputfile, dssp='/MYPATH/mambaforge/envs/Geopacker01/bin/mkdssp')
              print(type(dssp))
  
      if __name__ == "__main__":
          inputfile = '/MYPATH/GeoPacker/example/3MPC_A.pdb'
          pdbname = '3MPC'
          if 1:
              Test = Test_Dssp()
              Test.test_dssp(inputfile, pdbname)
          else:
              dssp_tuple = dssp_dict_from_pdb_file(inputfile)
              dssp_dict = dssp_tuple[0]
              print(dssp_dict['A',(' ', 1, ' ')])

## error 
>/root/mambaforge/lib/python3.9/site-packages/Bio/PDB/DSSP.py:252: UserWarning: parse error at line 1: This file does not >seem to be an mmCIF file
>
>  warnings.warn(err)
>Traceback (most recent call last):
>  File "/MYPATH/GeoPacker/my_scripts/test_dssp.py", line 26, in <module>
>   Test.test_dssp(inputfile, pdbname)
>  File "/MYPATH/GeoPacker/my_scripts/test_dssp.py", line 18, in test_dssp
>    dssp = DSSP(model,inputfile)
>  File "/root/mambaforge/lib/python3.9/site-packages/Bio/PDB/DSSP.py", line 438, in __init__
>   dssp_dict, dssp_keys = dssp_dict_from_pdb_file(in_file, dssp)
>  File "/root/mambaforge/lib/python3.9/site-packages/Bio/PDB/DSSP.py", line 254, in dssp_dict_from_pdb_file
>    raise Exception("DSSP failed to produce an output")
>Exception: DSSP failed to produce an output

It's weird that both ways of installing dssp got the same error, I think there must be some other problem.

I have also added this issue to dssp repo, hope someone can handle this...

**Comment by PKUliujl** [comment]
![1668234058](https://user-images.githubusercontent.com/110894511/201460563-c74e262e-74be-4f67-acef-2c59c8aa4ab0.jpg)

I have tested on different python versions including 3.7 and 3.9, and everything goes well. Attached screenshot is based on your provided python version for test. I hope it can provide you with some help and reference.

**Comment by kanghui-learning** [comment]
Thanks for this information. It's helpful. I found that mkdssp worked well with orders like that `mkdssp 6tiz.pdb`, while it takes about 20 seconds, I don't know if it's normal. And I noticed that you are using an earlier version of mkdssp, I'm trying to install one, which maybe works well together with biopython.
